#!/usr/bin/env python

import sys

from rqt_topic_display.number_display import NumberDisplay
from rqt_gui.main import Main

plugin = 'rqt_number_display'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
