#!/usr/bin/env python

import sys

from rqt_topic_display.topic_display import TopicDisplay
from rqt_gui.main import Main

plugin = 'rqt_topic_display'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
